// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnvmXCgKtwgPb1oY3Dzw77PFHEIiogsb0',
    appId: '1:180372478718:web:8e1ececc94e304ac0a63af',
    messagingSenderId: '180372478718',
    projectId: 'pawpulse-fd0c4',
    authDomain: 'pawpulse-fd0c4.firebaseapp.com',
    storageBucket: 'pawpulse-fd0c4.firebasestorage.app',
    measurementId: 'G-91CH9LLPD1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1rf4tIiT3fjoNCPsn_AeEYiWiP7ulD9c',
    appId: '1:180372478718:android:2814e7dd47a2245e0a63af',
    messagingSenderId: '180372478718',
    projectId: 'pawpulse-fd0c4',
    storageBucket: 'pawpulse-fd0c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbKZXQskt7SrNYCMeDOPFK8IQlpbcdwUI',
    appId: '1:180372478718:ios:be7f55a37acda8400a63af',
    messagingSenderId: '180372478718',
    projectId: 'pawpulse-fd0c4',
    storageBucket: 'pawpulse-fd0c4.firebasestorage.app',
    iosClientId: '180372478718-a15spuhjr3eui1ej35v89g73njoa8h4c.apps.googleusercontent.com',
    iosBundleId: 'com.example.pawpulse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbKZXQskt7SrNYCMeDOPFK8IQlpbcdwUI',
    appId: '1:180372478718:ios:be7f55a37acda8400a63af',
    messagingSenderId: '180372478718',
    projectId: 'pawpulse-fd0c4',
    storageBucket: 'pawpulse-fd0c4.firebasestorage.app',
    iosClientId: '180372478718-a15spuhjr3eui1ej35v89g73njoa8h4c.apps.googleusercontent.com',
    iosBundleId: 'com.example.pawpulse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnvmXCgKtwgPb1oY3Dzw77PFHEIiogsb0',
    appId: '1:180372478718:web:f27e0b20b85206e60a63af',
    messagingSenderId: '180372478718',
    projectId: 'pawpulse-fd0c4',
    authDomain: 'pawpulse-fd0c4.firebaseapp.com',
    storageBucket: 'pawpulse-fd0c4.firebasestorage.app',
    measurementId: 'G-7S4G9SJ9FL',
  );
}
